<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TransportSystem.Core.Domain\TransportSystem.Core.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Fleet\Drivers\Queries\GetDrivers\" />
    <Folder Include="Features\Fleet\Drivers\Queries\GetDriverById\" />
    <Folder Include="Features\Fleet\Drivers\Queries\GetAvailableDrivers\" />
    <Folder Include="Features\Fleet\Vehicles\Queries\GetVehicles\" />
    <Folder Include="Features\Fleet\Vehicles\Queries\GetVehicleById\" />
    <Folder Include="Features\Fleet\Vehicles\Queries\GetAvailableVehicles\" />
    <Folder Include="Features\Transportation\Queries\GetRequestById\" />
    <Folder Include="Features\Transportation\Queries\GetScheduleByDate\" />
    <Folder Include="Features\Transportation\Queries\GetDashboardSummary\" />
    <Folder Include="Features\Transportation\Queries\GetPendingRequests\" />
  </ItemGroup>

</Project>
