// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransportSystem.Infrastructure.Persistence.Contexts;

#nullable disable

namespace TransportSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260621235731_AddScheduledMaintenance")]
    partial class AddScheduledMaintenance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransportSystem.Core.Domain.Fleet.Aggregates.Driver.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Drivers_StatusId");

                    b.HasIndex("SupervisorId")
                        .HasDatabaseName("IX_Drivers_SupervisorId");

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("TransportSystem.Core.Domain.Fleet.Aggregates.Vehicle.FuelRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Gallons")
                        .HasColumnType("decimal(8,3)");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("PricePerGallon")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecordDate")
                        .HasDatabaseName("IX_FuelRecords_Date");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("IX_FuelRecords_VehicleId");

                    b.HasIndex("VehicleId", "RecordDate")
                        .HasDatabaseName("IX_FuelRecords_Vehicle_Date");

                    b.ToTable("FuelRecords", (string)null);
                });

            modelBuilder.Entity("TransportSystem.Core.Domain.Fleet.Aggregates.Vehicle.MaintenanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualExitDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EstimatedExitDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NextMaintenanceDateScheduled")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("MaintenanceTypeId");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Workshop")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EntryDate")
                        .HasDatabaseName("IX_Maintenance_EntryDate");

                    b.HasIndex("NextMaintenanceDateScheduled")
                        .HasDatabaseName("IX_Maintenance_NextDate");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("IX_Maintenance_VehicleId");

                    b.ToTable("MaintenanceRecords", (string)null);
                });

            modelBuilder.Entity("TransportSystem.Core.Domain.Fleet.Aggregates.Vehicle.ScheduledMaintenance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ResultingMaintenanceRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("MaintenanceTypeId");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Workshop")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledDate")
                        .HasDatabaseName("IX_ScheduledMaintenance_ScheduledDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ScheduledMaintenance_StatusId");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("IX_ScheduledMaintenance_VehicleId");

                    b.ToTable("ScheduledMaintenances", (string)null);
                });

            modelBuilder.Entity("TransportSystem.Core.Domain.Fleet.Aggregates.Vehicle.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("date");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("VehicleTypeId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Vehicles_StatusId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("TransportSystem.Core.Domain.Transportation.Aggregates.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PeriodDate")
                        .IsUnique()
                        .HasDatabaseName("UQ_Schedules_PeriodDate");

                    b.ToTable("Schedules", (string)null);
                });

            modelBuilder.Entity("TransportSystem.Core.Domain.Transportation.Aggregates.TravelRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedDriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedVehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestingArea")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<string>("TripPurpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId")
                        .HasDatabaseName("IX_TravelRequests_ApprovedBy");

                    b.HasIndex("RequestedByUserId")
                        .HasDatabaseName("IX_TravelRequests_RequestedBy");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_TravelRequests_StatusId");

                    b.ToTable("TravelRequests", (string)null);
                });

            modelBuilder.Entity("TransportSystem.Core.Domain.Transportation.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualDepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualReturnTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Assignments_RequestId");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("IX_Assignments_ScheduleId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Assignments_StatusId");

                    b.ToTable("Assignments", (string)null);
                });

            modelBuilder.Entity("TransportSystem.Core.Domain.Fleet.Aggregates.Driver.Driver", b =>
                {
                    b.OwnsOne("TransportSystem.Core.Domain.Fleet.Aggregates.Driver.DriverLicense", "License", b1 =>
                        {
                            b1.Property<Guid>("DriverId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Category")
                                .HasColumnType("int")
                                .HasColumnName("LicenseCategoryId");

                            b1.Property<DateTime>("ExpirationDate")
                                .HasColumnType("date")
                                .HasColumnName("LicenseExpirationDate");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LicenseNumber");

                            b1.HasKey("DriverId");

                            b1.HasIndex("ExpirationDate")
                                .HasDatabaseName("IX_Drivers_LicenseExpiry");

                            b1.HasIndex("Number")
                                .IsUnique()
                                .HasDatabaseName("UQ_Drivers_LicenseNumber");

                            b1.ToTable("Drivers");

                            b1.WithOwner()
                                .HasForeignKey("DriverId");
                        });

                    b.OwnsOne("TransportSystem.Core.Domain.Fleet.Aggregates.Driver.NationalId", "NationalId", b1 =>
                        {
                            b1.Property<Guid>("DriverId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("IdNumber");

                            b1.HasKey("DriverId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("UQ_Drivers_IdNumber");

                            b1.ToTable("Drivers");

                            b1.WithOwner()
                                .HasForeignKey("DriverId");
                        });

                    b.Navigation("License")
                        .IsRequired();

                    b.Navigation("NationalId")
                        .IsRequired();
                });

            modelBuilder.Entity("TransportSystem.Core.Domain.Fleet.Aggregates.Vehicle.FuelRecord", b =>
                {
                    b.HasOne("TransportSystem.Core.Domain.Fleet.Aggregates.Vehicle.Vehicle", null)
                        .WithMany("FuelRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TransportSystem.Core.Domain.Fleet.Aggregates.Vehicle.Mileage", "MileageAtRefuel", b1 =>
                        {
                            b1.Property<Guid>("FuelRecordId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("MileageAtRefuel");

                            b1.HasKey("FuelRecordId");

                            b1.ToTable("FuelRecords");

                            b1.WithOwner()
                                .HasForeignKey("FuelRecordId");
                        });

                    b.Navigation("MileageAtRefuel")
                        .IsRequired();
                });

            modelBuilder.Entity("TransportSystem.Core.Domain.Fleet.Aggregates.Vehicle.MaintenanceRecord", b =>
                {
                    b.HasOne("TransportSystem.Core.Domain.Fleet.Aggregates.Vehicle.Vehicle", null)
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TransportSystem.Core.Domain.Fleet.Aggregates.Vehicle.Mileage", "NextMaintenanceKmScheduled", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceRecordId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("NextMaintenanceKmScheduled");

                            b1.HasKey("MaintenanceRecordId");

                            b1.ToTable("MaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceRecordId");
                        });

                    b.Navigation("NextMaintenanceKmScheduled");
                });

            modelBuilder.Entity("TransportSystem.Core.Domain.Fleet.Aggregates.Vehicle.ScheduledMaintenance", b =>
                {
                    b.HasOne("TransportSystem.Core.Domain.Fleet.Aggregates.Vehicle.Vehicle", null)
                        .WithMany("ScheduledMaintenances")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TransportSystem.Core.Domain.Fleet.Aggregates.Vehicle.Mileage", "ScheduledKm", b1 =>
                        {
                            b1.Property<Guid>("ScheduledMaintenanceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("ScheduledKm");

                            b1.HasKey("ScheduledMaintenanceId");

                            b1.ToTable("ScheduledMaintenances");

                            b1.WithOwner()
                                .HasForeignKey("ScheduledMaintenanceId");
                        });

                    b.Navigation("ScheduledKm");
                });

            modelBuilder.Entity("TransportSystem.Core.Domain.Fleet.Aggregates.Vehicle.Vehicle", b =>
                {
                    b.OwnsOne("TransportSystem.Core.Domain.Fleet.Aggregates.Vehicle.LicensePlate", "LicensePlate", b1 =>
                        {
                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("LicensePlate");

                            b1.HasKey("VehicleId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("UQ_Vehicles_LicensePlate");

                            b1.ToTable("Vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.OwnsOne("TransportSystem.Core.Domain.Fleet.Aggregates.Vehicle.Mileage", "CurrentMileage", b1 =>
                        {
                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("decimal(10,2)")
                                .HasDefaultValue(0m)
                                .HasColumnName("Mileage");

                            b1.HasKey("VehicleId");

                            b1.ToTable("Vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.OwnsOne("TransportSystem.Core.Domain.Fleet.Aggregates.Vehicle.VehicleCapacity", "Capacity", b1 =>
                        {
                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Passengers")
                                .HasColumnType("int")
                                .HasColumnName("Capacity");

                            b1.HasKey("VehicleId");

                            b1.ToTable("Vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("CurrentMileage")
                        .IsRequired();

                    b.Navigation("LicensePlate")
                        .IsRequired();
                });

            modelBuilder.Entity("TransportSystem.Core.Domain.Transportation.Aggregates.TravelRequest", b =>
                {
                    b.OwnsOne("TransportSystem.Core.Domain.Transportation.ValueObjects.TimeSlot", "RequestedTimeSlot", b1 =>
                        {
                            b1.Property<Guid>("TravelRequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("DepartureTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DepartureDateTime");

                            b1.Property<DateTime>("ReturnTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ReturnDateTime");

                            b1.HasKey("TravelRequestId");

                            b1.ToTable("TravelRequests");

                            b1.WithOwner()
                                .HasForeignKey("TravelRequestId");
                        });

                    b.OwnsOne("TransportSystem.Core.Domain.Transportation.ValueObjects.Destination", "Destination", b1 =>
                        {
                            b1.Property<Guid>("TravelRequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("Destination");

                            b1.HasKey("TravelRequestId");

                            b1.ToTable("TravelRequests");

                            b1.WithOwner()
                                .HasForeignKey("TravelRequestId");
                        });

                    b.OwnsOne("TransportSystem.Core.Domain.Transportation.ValueObjects.RequestNumber", "RequestNumber", b1 =>
                        {
                            b1.Property<Guid>("TravelRequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("RequestNumber");

                            b1.HasKey("TravelRequestId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("UQ_TravelRequests_Number");

                            b1.ToTable("TravelRequests");

                            b1.WithOwner()
                                .HasForeignKey("TravelRequestId");
                        });

                    b.Navigation("Destination")
                        .IsRequired();

                    b.Navigation("RequestNumber")
                        .IsRequired();

                    b.Navigation("RequestedTimeSlot")
                        .IsRequired();
                });

            modelBuilder.Entity("TransportSystem.Core.Domain.Transportation.Entities.Assignment", b =>
                {
                    b.HasOne("TransportSystem.Core.Domain.Transportation.Aggregates.Schedule", null)
                        .WithMany("Assignments")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TransportSystem.Core.Domain.Transportation.ValueObjects.TimeSlot", "TimeSlot", b1 =>
                        {
                            b1.Property<Guid>("AssignmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("DepartureTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DepartureTime");

                            b1.Property<DateTime>("ReturnTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ReturnTime");

                            b1.HasKey("AssignmentId");

                            b1.ToTable("Assignments");

                            b1.WithOwner()
                                .HasForeignKey("AssignmentId");
                        });

                    b.Navigation("TimeSlot")
                        .IsRequired();
                });

            modelBuilder.Entity("TransportSystem.Core.Domain.Fleet.Aggregates.Vehicle.Vehicle", b =>
                {
                    b.Navigation("FuelRecords");

                    b.Navigation("MaintenanceRecords");

                    b.Navigation("ScheduledMaintenances");
                });

            modelBuilder.Entity("TransportSystem.Core.Domain.Transportation.Aggregates.Schedule", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
